### ISSUE TITLE
이걸 만들어 보라고 한 description을 알 수 있을까요?

### ISSUE THREAD

**Issue by jongfeel** [noobiny/ComboBox#2]

**Comment by noobiny** [comment]
1. 텍스트를 입력해서 콤보박스에 아이템 추가
2. 콤보박스의 각각의 아이템에 달려있는 버튼을 클릭하면 해당 아이템 삭제

이거 말씀이신가요?

**Comment by noobiny** [comment]
ComboBox.xaml 의 combobox의 ElementName 은 삭제해야 정상적으로 돌아가네요.

**Comment by jongfeel** [comment]
조건에 UserControl을 쓰라는 얘기가 있었나요? 억지로 만든 티가 나네요.

**Comment by noobiny** [comment]
네, 유저컨트롤로 만들라고 하셨습니다.

**Comment by jongfeel** [comment]
그러면 DependencyProperty를 쓰라는 얘기도 있었나요?

**Comment by noobiny** [comment]
아니요 그건 언급안했어요

**Comment by jongfeel** [comment]
UserControl 만들라고 하고 DependencyProperty 얘기는 없다니 반쪽짜리 문제네요.

**Comment by noobiny** [comment]
힌트가 되는 키워드 알려주실수있나요 검색해보니 콤보박스의 속성중 ElementName="root" 해서 이걸 이용한다는데 전혀 그렇게 이용하고있지 않아서요 ,
어떤데는 DelegateCommand<object> 이걸 사용하는데 이건 없는 클래스네요

**Comment by jongfeel** [comment]
MVVMLight를 쓰지 말라는 조건도 있던가요?

**Comment by noobiny** [comment]
아뇨, 저 방금 완료했어요, MVVMLight 는 제가 시도 해봤는데 설치가 안돼서 사용하지 못한거에요,
light는 설치가 됐는데 라이브러리들이 설치가 안되더라구요 gama~로 시작하는 라이브러리2개가,

해결방법은 CommandParameter={Binding} 으로 보내면 해당 커맨드의 object 파라미터에 자기자신이 넘어가더라구요( ObservableCollection <스트링>  ItemList )  를 이용할시,

**Comment by jongfeel** [comment]
문제가 있습니다.

만약 같은 string 값이 들어 있다면 어느 item을 지워야 할지 어떻게 판단할까요?

회사분들이 물어볼거 같은데요?

**Comment by noobiny** [comment]
아 그러네요 중복이 있다면 첫번째 꺼만 지워지네요 객체 형태로 만들어서 데이터를 관리해야겠어요

객체에다가 number 심어서 해볼게요

**Comment by jongfeel** [comment]
comment 달 동안 만들어 봤는데, pull 해보세요.

**Comment by noobiny** [comment]
우와 신기하네요 콤보박스아이템 형태로 만들면 되는군요, 저 객체형태로 만들어서 비교했어요

**Comment by jongfeel** [comment]
그래도 되는데, equal을 구현해야 하니
이미 구현되어 있는 ComboboxItem을 쓰면 편합니다.
